<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0-windows</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <UseWindowsForms>true</UseWindowsForms>
	  <UseWPF>True</UseWPF>
	  <Platforms>AnyCPU;x64;x86</Platforms>
	  <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
	  <PlatformTarget>AnyCPU</PlatformTarget>
	  <NoWarn>CA1416</NoWarn>
	  <SignAssembly>True</SignAssembly>
	  <AssemblyOriginatorKeyFile>E:\TheBook.Net\signature-files(keep private)\TheBook.Net\keypair.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>none</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>none</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <Optimize>True</Optimize>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DebugType>none</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AdvRichTextBox.cs" />
    <Compile Remove="myNodeTreeRegistry.cs" />
    <Compile Remove="RichTextBoxEx.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HtmlAgilityPack\HtmlAgilityPack.csproj" />
    <ProjectReference Include="..\MarkupConverter\MarkupConverter.csproj" />
    <ProjectReference Include="..\MigraDocPlusXml\MigraDocPlusXml.csproj" />
    <ProjectReference Include="..\PdfSharp\PDFsharp.csproj" />
    <ProjectReference Include="..\RtfPipe\RtfPipe.csproj" />
    <ProjectReference Include="..\RtfWriter\RtfWriter.csproj" />
    <ProjectReference Include="..\TheArtOfDev.HtmlRenderer.PdfSharp\TheArtOfDev.HtmlRenderer.PdfSharp.csproj" />
    <ProjectReference Include="..\TheArtOfDev.HtmlRenderer\TheArtOfDev.HtmlRenderer.csproj" />
    <ProjectReference Include="..\YamlDotNet\YamlDotNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
